### ISSUE TITLE
p34v5 

### ISSUE THREAD

**Issue by deechoe** [sztupy/Gigabyte-P34W-v3-OSX86#2]
Is it possible to use the Nvidia video card?

I have the p34v5 and was hoping to install OSX Sierra on it.  Any info or has anyone successfully install OSX on p34v5?  

CPU: Intel i7 6700hq (skylake)
display adapter: Intel 530
bios: fb10

**Comment by sztupy** [comment]
You can't use NVidia with Optimus technology (=most notebooks with both nvidia and Intel GPUs) on OSX86, so you have to disable the dedicated GPU completely. There are no workarounds yet, and most likely will not be in the near or far future.
